### ISSUE TITLE
Revisit colors for light and projection screen.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/geometric-optics#226]
I find the yellow spot very hard to pick out on the projection screen. 

A screen will only be "white" if there is actually light shining on it and reflecting back into your eye. In this case, the only light in the room is the spotlight, so in fact, you will see a bright yellow spot and the rest of the screen will be dark. Thus, I think we should set the background of the projection screen back to a dark grey - just slightly less dark than the background overall. It is more accurate physics, and easier to see.

I would suggest making this change for the prototype. 

@arouinfar - Thoughts?

**Comment by pixelzoom** [comment]
So to summarize...  The current proposal is to stick with the white screen color.  And the difficulty seeing low-intensity spots on the screen is addressed in #240.

@kathy-phet @ariel-phet are you OK with this for the prototype? And in general?

**Comment by kathy-phet** [comment]
I’m still having a physics issue with the white screen. A very dark grey, just a bit lighter than the background black, is correct physics. Think about a spotlight in a dark room, which is what we have created here. You only see the spot, not the screen.

**Comment by pixelzoom** [comment]
This suggestion will result in no change to brightness as intensity changes.  Instead, the hue will change.  That seems problematic to me, because brightness, in physics, is the subjective visual sensation related to the intensity of light emanating from a surface or from a point source. https://www.britannica.com/science/brightness-light

**Comment by pixelzoom** [comment]
Since I think we have a serious problem here with using 'red' light, also assigning to @kathy-phet and @ariel-phet for review.

**Comment by pixelzoom** [comment]
The screenshot below shows the blue bulbs and spots in context.  (I did not commit this.).  

Using blue does avoid the "red for second point" problem.  But blue is also the color used for the lens, and the opacity of that blue changes with index of refraction. Do we really want to use blue, and change it's opacity, for 2 different (unrelated) things?  Blue-on-black is also one of the most notoriously-bad color combinations.

So I confirmed with @arouinfar on Slacik.  We'll revert this issue and #240 (dashed outline) to where things were before this morning's design meeting, create the prototye RC branch, then revisit colors for the public publication.

<img width="1174" alt="screenshot_1379" src="https://user-images.githubusercontent.com/3046552/137818610-7cc9daf1-5887-45bf-9478-5bdd53a80c70.png">
.

**Comment by pixelzoom** [comment]
We're back to this for the prototype, see screenshot below.  I'll remove the "Prototype" milestone from this issue, tweak the title of this issue, and we can revisit for the final version.

<img width="1173" alt="screenshot_1380" src="https://user-images.githubusercontent.com/3046552/137819722-28a09db4-10b6-4d71-9015-85d249f7aa53.png">

**Comment by arouinfar** [comment]
Color changes will be addressed in #319, closing.
